---
# tasks file for vagrantbox-pack
- name: Use packer to build the base box if it does not already exists
  shell: packer build {{ vm }}.json
  args:
    chdir: "{{ ansible_env.PWD }}/../packer"
    creates: "{{ ansible_env.PWD }}/../packer/{{ vm }}.box"
